### ISSUE TITLE
using advanced search or external field

### ISSUE THREAD

**Issue by manaka02** [HelloSebastian/hello-bootstrap-table-bundle#30]
Hello, 
First, really thanks for your works ! I'm new on it and on Boostrap table ! I want to create a custom filter (using multiple field with checkbox, dateInterval ,  ....). My question is, if I have a form, how can I pass all the value to the datatable, and how can I refresh the table manually ! 

Cheers !

**Comment by manaka02** [comment]
![image](https://user-images.githubusercontent.com/26122514/193235330-e55ed294-10c1-4201-a5bc-031033dc0650.png)

**Comment by manaka02** [comment]
![image](https://user-images.githubusercontent.com/26122514/193235791-06b332a8-1fc7-4409-9b2f-b3209ee57df7.png)

**Comment by HelloSebastian** [comment]
Hi,

thank you very much for the kind words.

As I see in the form, many fields also exist as columns in the table. Wouldn't that be easier to filter column by column? That means that the input fields are under the spade header.

But probably you also have fields that do not exist as columns in the table.

HelloBootrapTable evaluates POST request. This is done in https://github.com/HelloSebastian/hello-bootstrap-table-bundle/blob/c05fbccedf7c7465ab3fce11b05606d5a6fcdc2a/src/Response/TableResponse.php. So if you want to make a query manually using your form, you have to follow the structure fields in the body:
https://github.com/HelloSebastian/hello-bootstrap-table-bundle/blob/c05fbccedf7c7465ab3fce11b05606d5a6fcdc2a/src/Response/TableResponse.php#L89-L99

So you have to use jQuery (or vanillia JS) to format the data of your form and set "isCallback" to "true". Then HelloBootstrapTable evaluates your filtering and returns the data via JSON. You then need to pass this data into the bootstrap-table instance.

So that you can also filter for values that are not in the table as columns, you must still insert them into the table (then as HiddenColumn).

But with this solution you will get a problem if you want to sort the columns. Since the table doesn't know about your form, the input will not be taken into account when sorting.

I must honestly say that I have not (yet) considered this use-case and thus the implementation misses the actual workflow.

I would advise you to enable column-by-column filtering and not to create an additional form. But I still hope I could help you with my solution.

Feel free to give me feedback if this worked.
